version: '3'
services:
  # Servicio para la API
  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mongo-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://devfs031023:access123@mongodb:27017/usersBoot?authSource=admin

  # Servicio para MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devfs031023
      - MONGO_INITDB_ROOT_PASSWORD=access123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - mongo-network

# Definir los volúmenes
volumes:
  mongo_data:

# Definir las redes
networks:
  mongo-network:
    driver: bridge


